name: "Cargo Tests"
on:
  pull_request:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      chroma:
        image: 'chromadb/chroma:latest'
        ports:
          - '8000:8000'
    
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test
